import React from 'react';
import NavBar from '@/components/NavBar/NavBar';
import 'tailwindcss/tailwind.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="../output.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="font-inter  text-white
      w-full h-screen bg-gradient-to-b from-general_bg to-cards_bg
      ">
        {/* particulas */}
        <NavBar />
        <div>
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
