import React from 'react';
import NavBar from '@/components/NavBar';
import 'tailwindcss/tailwind.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="../output.css" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="font-inter">
        <NavBar />
        <div>
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
